builds:
  - main: cmd/lock/main.go
    binary: lock
    goos:
      - linux
    goarch:
      - 386
      - amd64
    env:
      - CGO_ENABLED=0

archive:
  format_overrides:
    - goos: linux
      format: .tar.gz