language: go

go: 1.11.x

install: true

script:
- GO111MODULE=on go test -v -cover ./...

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | GO111MODULE=on bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

cache:
  directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod