language: go

go: 1.10.x

script:
  - go test -v -cover ./...

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg