[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "^6.10.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"
